### ISSUE TITLE
Processing Speed

### ISSUE THREAD

**Issue by niallobr** [chacawaca/docker-post-recording#10]
I noticed with vaapi hwaccel it's still taking around 10 hours to complete the conversion of a 1 hour .ts file. Are there any tips for speeding up the process? Even obvious things like lowering the quality slightly? 

Apologies if this is more of a general ffmpeg question. I thought it might help some others out.

Here's what I currently have in custom.sh

`ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -i "$INPUT" -vf 'format=nv12|vaapi,hwupload,deinterlace_vaapi' -preset fast -threads 8 -c:v h264_vaapi -brand mp42 -ac 2 -c:a ac3 -b:a 106K "$OUTPUT"`

I was trying to experiment with the **preset** command but didn't notice much difference. I also tried playing with the **crf** option. After playing around some conversions take just over an hour, others 3-4 hours.

### Enhancement idea 

if the script detects h264 video and you have set that as a preferred format then it just copies the video stream into the mp4 container, but if it detects a non-preferred format then the video is re-encoded, could that work?

**Comment by chacawaca** [comment]
its more a ffmpeg question, a part i dont want(have time) to support.
