### ISSUE TITLE
Make a version of that runs on an ARM64 processor

### ISSUE THREAD

**Issue by bobcoup** [chacawaca/docker-post-recording#8]
Hi

I am very interested in this docker image as I think it does what I want. How easy would it be to create a docker image from this that runs on ARM64?

Most of the contents of the Dockerfile look like no changes are required. It was only the "COPY --from=djaydev/baseimage-s6overlay:amd64 /tmp/ /" line that would need changing to use the arm64 version.

Thanks.

**Comment by chacawaca** [comment]
Sorry i dont have time to support more build, you still can fork it and do your own version.
